# =============================================================================
# NexGen - Makefile
# =============================================================================
# Generated by MIA BUILD
# =============================================================================

.PHONY: up down logs status restart clean build test

# Default target
.DEFAULT_GOAL := up

# Start all services
up:
	@./run.sh up

# Stop all services
down:
	@./run.sh down

# View logs
logs:
	@./run.sh logs

# Check status
status:
	@./run.sh status

# Restart services
restart:
	@./run.sh restart

# Clean up
clean:
	@./run.sh clean

# Build images
build:
	@docker-compose build

# Run tests
test:
	@docker-compose run --rm api npm test

# Database migrations
migrate:
	@docker-compose exec postgres psql -U postgres -d app -f /docker-entrypoint-initdb.d/001_init.sql

# Seed database
seed:
	@docker-compose exec api npm run seed

# Shell into API container
shell-api:
	@docker-compose exec api sh

# Shell into database
shell-db:
	@docker-compose exec postgres psql -U postgres -d app
