#!/bin/bash

# =============================================================================
# NexGen - Run Script
# =============================================================================
# Generated by MIA BUILD
# Usage: ./run.sh [command]
#
# Commands:
#   up      - Start all services
#   down    - Stop all services
#   logs    - View service logs
#   status  - Check service status
#   restart - Restart all services
#   clean   - Remove all containers and volumes
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Load environment if exists
if [ -f .env ]; then
    export $(cat .env | grep -v "^#" | xargs)
fi

# Default command
COMMAND="${1:-up}"

case "$COMMAND" in
    up)
        echo "Starting services..."
        docker-compose up -d
        echo ""
        echo "Services started. Access points:"
        echo "  - API:      http://lokalni-streznik:3000"
        echo "  - UI:       http://lokalni-streznik:8080"
        echo "  - Keycloak: http://lokalni-streznik:8180"
        echo "  - Grafana:  http://lokalni-streznik:3001"
        echo ""
        echo "Run './run.sh logs' to view logs"
        ;;
    down)
        echo "Stopping services..."
        docker-compose down
        echo "Services stopped."
        ;;
    logs)
        docker-compose logs -f
        ;;
    status)
        docker-compose ps
        ;;
    restart)
        echo "Restarting services..."
        docker-compose restart
        echo "Services restarted."
        ;;
    clean)
        echo "Removing all containers and volumes..."
        docker-compose down -v --remove-orphans
        echo "Cleanup complete."
        ;;
    *)
        echo "Unknown command: $COMMAND"
        echo "Usage: ./run.sh [up|down|logs|status|restart|clean]"
        exit 1
        ;;
esac
