-- =============================================================================
-- NexGen - Seed Data
-- =============================================================================
-- Generated by MIA BUILD
-- =============================================================================

-- Insert default admin user
INSERT INTO users (id, email, name) VALUES 
    ('00000000-0000-0000-0000-000000000001', 'admin@primer.com', 'Administrator')
ON CONFLICT (email) DO NOTHING;

-- Insert vzorec audit log entry
INSERT INTO audit_log (user_id, action, entity_type, entity_id, details) VALUES 
    ('00000000-0000-0000-0000-000000000001', 'SYSTEM_INIT', 'system', NULL, '{"message": "System initialized"}')
ON CONFLICT DO NOTHING;
